// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type UsersRole string

const (
	UsersRoleUser      UsersRole = "user"
	UsersRoleAdmin     UsersRole = "admin"
	UsersRoleModerator UsersRole = "moderator"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type UsersSubscriptionTier string

const (
	UsersSubscriptionTierFree  UsersSubscriptionTier = "free"
	UsersSubscriptionTierBasic UsersSubscriptionTier = "basic"
	UsersSubscriptionTierPro   UsersSubscriptionTier = "pro"
)

func (e *UsersSubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersSubscriptionTier(s)
	case string:
		*e = UsersSubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersSubscriptionTier: %T", src)
	}
	return nil
}

type NullUsersSubscriptionTier struct {
	UsersSubscriptionTier UsersSubscriptionTier `json:"users_subscription_tier"`
	Valid                 bool                  `json:"valid"` // Valid is true if UsersSubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.UsersSubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersSubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersSubscriptionTier), nil
}

type User struct {
	ID               int64                 `db:"id" json:"id"`
	Name             string                `db:"name" json:"name"`
	Surname          string                `db:"surname" json:"surname"`
	Age              sql.NullInt32         `db:"age" json:"age"`
	CountryCode      sql.NullString        `db:"country_code" json:"country_code"`
	AccountBalance   sql.NullString        `db:"account_balance" json:"account_balance"`
	Role             UsersRole             `db:"role" json:"role"`
	IsPremium        sql.NullBool          `db:"is_premium" json:"is_premium"`
	SubscriptionTier UsersSubscriptionTier `db:"subscription_tier" json:"subscription_tier"`
	Timezone         sql.NullString        `db:"timezone" json:"timezone"`
}
