// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserWithID(ctx context.Context, arg CreateUserWithIDParams) (sql.Result, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
