// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    name,
    surname,
    age,
    country_code,
    role,
    is_premium,
    subscription_tier,
    account_balance,
    timezone
) VALUES (
             ?, ?, ?, ?, ?, ?, ?, ?, ?
         )
`

type CreateUserParams struct {
	Name             string                `db:"name" json:"name"`
	Surname          string                `db:"surname" json:"surname"`
	Age              sql.NullInt32         `db:"age" json:"age"`
	CountryCode      sql.NullString        `db:"country_code" json:"country_code"`
	Role             UsersRole             `db:"role" json:"role"`
	IsPremium        sql.NullBool          `db:"is_premium" json:"is_premium"`
	SubscriptionTier UsersSubscriptionTier `db:"subscription_tier" json:"subscription_tier"`
	AccountBalance   sql.NullString        `db:"account_balance" json:"account_balance"`
	Timezone         sql.NullString        `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Surname,
		arg.Age,
		arg.CountryCode,
		arg.Role,
		arg.IsPremium,
		arg.SubscriptionTier,
		arg.AccountBalance,
		arg.Timezone,
	)
	return err
}

const createUserWithID = `-- name: CreateUserWithID :execresult
INSERT INTO users (
    name,
    surname,
    age,
    country_code,
    role,
    is_premium,
    subscription_tier,
    account_balance,
    timezone
) VALUES (
             ?, ?, ?, ?, ?, ?, ?, ?, ?
         )
`

type CreateUserWithIDParams struct {
	Name             string                `db:"name" json:"name"`
	Surname          string                `db:"surname" json:"surname"`
	Age              sql.NullInt32         `db:"age" json:"age"`
	CountryCode      sql.NullString        `db:"country_code" json:"country_code"`
	Role             UsersRole             `db:"role" json:"role"`
	IsPremium        sql.NullBool          `db:"is_premium" json:"is_premium"`
	SubscriptionTier UsersSubscriptionTier `db:"subscription_tier" json:"subscription_tier"`
	AccountBalance   sql.NullString        `db:"account_balance" json:"account_balance"`
	Timezone         sql.NullString        `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateUserWithID(ctx context.Context, arg CreateUserWithIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserWithID,
		arg.Name,
		arg.Surname,
		arg.Age,
		arg.CountryCode,
		arg.Role,
		arg.IsPremium,
		arg.SubscriptionTier,
		arg.AccountBalance,
		arg.Timezone,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, surname, age, country_code, account_balance, role, is_premium, subscription_tier, timezone FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Age,
		&i.CountryCode,
		&i.AccountBalance,
		&i.Role,
		&i.IsPremium,
		&i.SubscriptionTier,
		&i.Timezone,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, surname, age, country_code, account_balance, role, is_premium, subscription_tier, timezone FROM users WHERE name = ? AND surname = ? LIMIT 1
`

type GetUserByUsernameParams struct {
	Name    string `db:"name" json:"name"`
	Surname string `db:"surname" json:"surname"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, arg.Name, arg.Surname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Age,
		&i.CountryCode,
		&i.AccountBalance,
		&i.Role,
		&i.IsPremium,
		&i.SubscriptionTier,
		&i.Timezone,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?,
    surname = ?,
    age = ?,
    country_code = ?,
    timezone = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name        string         `db:"name" json:"name"`
	Surname     string         `db:"surname" json:"surname"`
	Age         sql.NullInt32  `db:"age" json:"age"`
	CountryCode sql.NullString `db:"country_code" json:"country_code"`
	Timezone    sql.NullString `db:"timezone" json:"timezone"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Surname,
		arg.Age,
		arg.CountryCode,
		arg.Timezone,
		arg.ID,
	)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role UsersRole `db:"role" json:"role"`
	ID   int64     `db:"id" json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
